services:
  postgres:
    image: postgres:14.17
    container_name: recime-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recime_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recime-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  recime-network:
    driver: bridge